### Register a new account
POST {{host}}/auth/register
Content-Type: application/json

{
  "email": "test@example.com",
  "password": "YourPassword123!"
}

### Login
POST {{host}}/auth/login
Content-Type: application/json

{
    "email": "test@example.com",
    "password": "YourPassword123!"
}

> {%
    client.global.set("token", response.body.accessToken);
%}

### Get my profile (requires login first)
GET {{host}}/auth/me
Authorization: Bearer {{token}}
